import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavHeader from "@/components/structure/header/header";
import Footer from "@/components/structure/footer/footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Head from "next/head";
config.autoAddCss = false;
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          src="https://kit.fontawesome.com/gaggleapp.js"
          crossOrigin="anonymous"
          async
        ></script>
      </Head>

      <body
        className={cn(
          "bg-background font-sans antialiased bg-slate-200",
          fontSans.variable
        )}
      >
        <NavHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
