import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { config } from "@fortawesome/fontawesome-svg-core";
import { ThemeProvider } from "@mui/material/styles";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Head from "next/head";
import theme from "@/theme";
import HeaderSection from "@/components/header/header";
import ResponsiveAppBar from "@/components/header2/Header2";
import { SessionProvider } from "next-auth/react";
config.autoAddCss = false;
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link href="https://fonts.googleapis.com/css2?family=Metamorphous&display=swap" rel="stylesheet" />
          <script src="https://kit.fontawesome.com/gaggleapp.js" crossOrigin="anonymous" async></script>
        </Head>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <body className={cn("font-sans antialiased bg-slate-200", fontSans.variable)}>
              <ResponsiveAppBar />
              {children}
            </body>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </SessionProvider>
    </html>
  );
}
